from views import *
from reports import *
from materias_primas import *
from currentsettings import *
from devolucoes import *
from bobinagens import *
from bobines import *
from paletes import *
from ordens_fabrico import *
from app_permissions import *
from artigos import *
from exports import *
from qualidade import *
from eventos import *
from cargas import *
from print import *
from sage import *
from reciclado import *
from exportdata_A01 import *
from trocaetiquetas import *
from producao.api.urls import *

