from views import *
from reports import *
from materias_primas import *
from currentsettings import *
from devolucoes import *
from bobinagens import *
from paletes import *
from print import *
from producao.api.urls import *
