# Generated by Django 3.2.8 on 2021-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemFabricoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowid', models.BigIntegerField(unique=True, verbose_name='SAGE ROWID Ordem Fabrico')),
                ('cod', models.BigIntegerField(unique=True, verbose_name='SAGE MFGNUM_0 Número Ordem Fabrico')),
            ],
        ),
    ]
