# Generated by Django 3.2.8 on 2021-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_ordemfabricodetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowid', models.BigIntegerField(unique=True, verbose_name='SAGE ROWID Artigo')),
                ('cod', models.CharField(max_length=25, unique=True, verbose_name='SAGE ITMREF_0 Código Artigo')),
            ],
        ),
        migrations.CreateModel(
            name='EncomendaDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowid', models.BigIntegerField(unique=True, verbose_name='SAGE ROWID Encomenda')),
                ('cod', models.CharField(max_length=25, unique=True, verbose_name='SAGE SOHNUM_0 Encomenda')),
            ],
        ),
        migrations.AlterField(
            model_name='ordemfabricodetails',
            name='cod',
            field=models.CharField(max_length=25, unique=True, verbose_name='SAGE MFGNUM_0 Número Ordem Fabrico'),
        ),
    ]
