# Generated by Django 3.2.8 on 2021-10-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_artigodetails_encomendadetails_ordemfabricodetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemfabricodetails',
            name='ignorar',
            field=models.SmallIntegerField(default=1, verbose_name='SAGE 1 - Ignorar Ordem de Produção | 0 - Não Ignorar'),
        ),
    ]
