# Generated by Django 3.2.8 on 2021-10-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_ordemfabricodetails_ignorar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemfabricodetails',
            name='rowid',
        ),
    ]
