# Generated by Django 3.2.8 on 2021-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0005_remove_ordemfabricodetails_rowid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_alt', models.SmallIntegerField(default=10, verbose_name='SAGE BOMALT_0 BOM Alternativo por Artigo')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Produto Acabado')),
                ('artigo_des', models.CharField(max_length=100, verbose_name='SAGE ITMDES1_0 Designação Produto Acabado')),
                ('matprima_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Matéria Prima')),
                ('matprima_des', models.CharField(max_length=100, verbose_name='SAGE ITMDES1_0 Designação Matéria Prima')),
                ('qty_base', models.DecimalField(decimal_places=13, max_digits=28, verbose_name='SAGE BASQTY_0 Quantidade Base (Razão)')),
                ('updatedate_bom', models.DateTimeField(auto_now=True, verbose_name='SAGE UPDDAT_0 Update Date do BOM')),
                ('updatedate_bomd', models.DateTimeField(auto_now=True, verbose_name='SAGE UPDDAT_0 Update Date da Matéria Prima BOM')),
                ('matprima_unidade', models.CharField(max_length=5, verbose_name='SAGE BOMUOM_0 Unidade de Medida Matéria Prima')),
                ('qty', models.DecimalField(decimal_places=13, max_digits=28, verbose_name='SAGE BOMQTY_0 Quantidade Matéria Prima')),
            ],
        ),
    ]
