# Generated by Django 3.2.8 on 2021-10-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0007_alter_bomitems_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitems',
            name='fromsage',
            field=models.SmallIntegerField(default=0, verbose_name='Coluna de controlo para indicar se a importação foi pelo SAGE 1 sim 0 não'),
        ),
    ]
