# Generated by Django 3.2.8 on 2021-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_bomitems_fromsage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitems',
            name='bom_seq',
            field=models.SmallIntegerField(default=5, verbose_name='SAGE BOMSEQ_0 Sequência BOM do Artigo'),
        ),
    ]
