# Generated by Django 3.2.8 on 2021-11-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0010_alter_bomitems_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paletizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_cod', models.PositiveIntegerField(verbose_name='SAGE BPCORD_0 Código de cliente')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Produto Acabado')),
                ('contentor_id', models.SmallIntegerField(verbose_name='Id do Contentor')),
                ('filmeestiravel_bobines', models.SmallIntegerField(default=0, verbose_name='Filme Estirável por Bobines')),
                ('filmeestiravel_exterior', models.SmallIntegerField(default=0, verbose_name='Filme Estirável Exterior')),
                ('cintas', models.SmallIntegerField(default=0, verbose_name='Cintas por Palete Sim/Não')),
                ('ncintas', models.SmallIntegerField(default=0, verbose_name='Número ce Cintas por Palete')),
                ('paletes_sobrepostas', models.SmallIntegerField(default=0, verbose_name='Paletes Sobrepostas')),
                ('npaletes', models.SmallIntegerField(verbose_name='Número Paletes por Contentor')),
                ('palete_maxaltura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Altura Máxima da Palete')),
                ('netiquetas_bobine', models.SmallIntegerField(verbose_name='Número Etiquetas por Bobine')),
                ('netiquetas_lote', models.SmallIntegerField(verbose_name='Número de Etiquetas do Lote')),
                ('netiquetas_final', models.SmallIntegerField(verbose_name='Número de Etiquetas Final')),
            ],
            options={
                'unique_together': {('cliente_cod', 'artigo_cod', 'contentor_id')},
            },
        ),
        migrations.CreateModel(
            name='PaletizacaoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.SmallIntegerField(verbose_name='Id do Item')),
                ('item_des', models.CharField(max_length=100, verbose_name='Item designação')),
                ('item_order', models.SmallIntegerField(verbose_name='Item Ordem')),
                ('item_numbobines', models.SmallIntegerField(verbose_name='Item Número de Bobines')),
                ('item_paletesize', models.CharField(max_length=20, verbose_name='Item Tamanho Palete')),
                ('paletizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.paletizacao', verbose_name='Paletização')),
            ],
        ),
    ]
