# Generated by Django 3.2.8 on 2021-11-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0011_paletizacao_paletizacaodetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletizacao',
            name='designacao',
            field=models.CharField(max_length=20, null=True, verbose_name='Designação'),
        ),
        migrations.AlterUniqueTogether(
            name='paletizacao',
            unique_together={('designacao', 'cliente_cod', 'artigo_cod', 'contentor_id')},
        ),
    ]
