# Generated by Django 3.2.8 on 2021-11-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0012_auto_20211102_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletizacao',
            name='cintas_palete',
            field=models.SmallIntegerField(default=1, verbose_name='Aplicar Cintas em 1-Ambas as Paletes | 2-Palete Superior | 3-Palete Inferior'),
        ),
        migrations.AlterField(
            model_name='paletizacao',
            name='filmeestiravel_bobines',
            field=models.SmallIntegerField(default=0, verbose_name='Filme Estirável por Palete'),
        ),
    ]
