# Generated by Django 3.2.8 on 2021-11-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0013_auto_20211104_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paletizacao',
            name='contentor_id',
            field=models.CharField(max_length=8, verbose_name='Id do Contentor'),
        ),
    ]
