# Generated by Django 3.2.8 on 2021-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0014_alter_paletizacao_contentor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paletizacaodetails',
            name='item_numbobines',
            field=models.SmallIntegerField(null=True, verbose_name='Item Número de Bobines'),
        ),
        migrations.AlterField(
            model_name='paletizacaodetails',
            name='item_paletesize',
            field=models.CharField(max_length=20, null=True, verbose_name='Item Tamanho Palete'),
        ),
    ]
