# Generated by Django 3.2.8 on 2021-11-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0015_auto_20211104_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOrdemFabrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_id', models.CharField(max_length=25, null=True, verbose_name='Ordem de Produção')),
                ('order_cod', models.CharField(max_length=25, null=True, verbose_name='Código Encomenda')),
                ('prf_cod', models.CharField(max_length=25, null=True, verbose_name='Código PRF')),
                ('cliente_cod', models.CharField(max_length=15, null=True, verbose_name='Código Cliente')),
                ('cliente_nome', models.CharField(max_length=80, null=True, verbose_name='Nome Cliente')),
                ('item_cod', models.CharField(max_length=25, null=True, verbose_name='Código Artigo')),
                ('paletizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.paletizacao', verbose_name='Paletização')),
            ],
            options={
                'unique_together': {('of_id', 'item_cod', 'cliente_cod', 'order_cod')},
            },
        ),
    ]
