# Generated by Django 3.2.8 on 2021-11-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0016_tempordemfabrico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=50, null=True, verbose_name='Designação')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Produto Acabado')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('extr0', models.CharField(default='A', max_length=2, verbose_name='Extrusora 0')),
                ('extr1', models.CharField(default='C', max_length=2, verbose_name='Extrusora 1')),
                ('extr2', models.CharField(default='B', max_length=2, verbose_name='Extrusora 2')),
                ('extr3', models.CharField(default='C', max_length=2, verbose_name='Extrusora 3')),
                ('extr4', models.CharField(default='A', max_length=2, verbose_name='Extrusora 4')),
                ('extr0_val', models.DecimalField(decimal_places=1, default=5, max_digits=4, verbose_name='Extrusora 0 Valor %')),
                ('extr1_val', models.DecimalField(decimal_places=1, default=22.5, max_digits=4, verbose_name='Extrusora 1 Valor %')),
                ('extr2_val', models.DecimalField(decimal_places=1, default=45, max_digits=4, verbose_name='Extrusora 2 Valor %')),
                ('extr3_val', models.DecimalField(decimal_places=1, default=22.5, max_digits=4, verbose_name='Extrusora 3 Valor %')),
                ('extr4_val', models.DecimalField(decimal_places=1, default=5, max_digits=4, verbose_name='Extrusora 4 Valor %')),
            ],
        ),
        migrations.CreateModel(
            name='FormulacaoParametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.formulacao', verbose_name='Formulacao')),
            ],
        ),
        migrations.CreateModel(
            name='FormulacaoMateriasPrimas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matprima_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Matéria Prima')),
                ('matprima_des', models.CharField(max_length=100, verbose_name='SAGE ITMDES1_0 Designação Matéria Prima')),
                ('formulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.formulacao', verbose_name='Formulacao')),
            ],
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='formulacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.formulacao', verbose_name='Formulação'),
        ),
    ]
