# Generated by Django 3.2.8 on 2021-11-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0017_auto_20211108_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacaomateriasprimas',
            name='arranque',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Arranque'),
        ),
        migrations.AddField(
            model_name='formulacaomateriasprimas',
            name='densidade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Densidade'),
        ),
        migrations.AddField(
            model_name='formulacaomateriasprimas',
            name='extrusora',
            field=models.CharField(default='A', max_length=2, verbose_name='Extrusora'),
        ),
        migrations.AddField(
            model_name='formulacaomateriasprimas',
            name='tolerancia',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=4, verbose_name='Tolerância'),
        ),
        migrations.AddField(
            model_name='formulacaomateriasprimas',
            name='vglobal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Valor Global'),
        ),
        migrations.AlterField(
            model_name='formulacaomateriasprimas',
            name='matprima_des',
            field=models.CharField(max_length=100, null=True, verbose_name='SAGE ITMDES1_0 Designação Matéria Prima'),
        ),
    ]
