# Generated by Django 3.2.8 on 2021-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0018_auto_20211110_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacao',
            name='versao',
            field=models.SmallIntegerField(default=1, verbose_name='Versão'),
        ),
    ]
