# Generated by Django 3.2.8 on 2021-11-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0020_auto_20211115_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamasoperatoriasitems',
            name='item_key',
            field=models.CharField(max_length=100, null=True, verbose_name='Chave do Item'),
        ),
        migrations.AddField(
            model_name='gamasoperatoriasitems',
            name='item_nvalues',
            field=models.SmallIntegerField(default=1, verbose_name='Nº de Valores'),
        ),
    ]
