# Generated by Django 3.2.8 on 2021-11-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0021_auto_20211115_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamasoperatoriasitems',
            name='item_values',
            field=models.JSONField(null=True, verbose_name='Valores do Item'),
        ),
    ]
