# Generated by Django 3.2.8 on 2021-11-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0022_alter_gamasoperatoriasitems_item_values'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamasOperatoriasItems',
            new_name='GamaOperatoriaItems',
        ),
    ]
