# Generated by Django 3.2.8 on 2021-11-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0023_rename_gamasoperatoriasitems_gamaoperatoriaitems'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formulacao',
            unique_together={('artigo_cod', 'designacao', 'versao')},
        ),
    ]
