# Generated by Django 3.2.8 on 2021-11-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0026_alter_formulacao_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulacaomateriasprimas',
            name='arranque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Arranque'),
        ),
        migrations.AlterField(
            model_name='formulacaomateriasprimas',
            name='densidade',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Densidade'),
        ),
        migrations.AlterField(
            model_name='formulacaomateriasprimas',
            name='tolerancia',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=6, verbose_name='Tolerância'),
        ),
        migrations.AlterField(
            model_name='formulacaomateriasprimas',
            name='vglobal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor Global'),
        ),
    ]
