# Generated by Django 3.2.8 on 2021-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0030_rename_gamaoperatoria_tempordemfabrico_gamaoperatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasTecnicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Produto Acabado')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('item_des', models.CharField(max_length=100, null=True, verbose_name='Designação do Item')),
                ('item_values', models.JSONField(null=True, verbose_name='Valores do Item')),
                ('item_key', models.CharField(max_length=100, null=True, verbose_name='Chave do Item')),
            ],
        ),
    ]
