# Generated by Django 3.2.8 on 2021-11-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0033_delete_caracteristicastecnicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=50, null=True, verbose_name='Designação')),
                ('versao', models.SmallIntegerField(default=1, verbose_name='Versão')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Produto Acabado')),
                ('cliente_cod', models.CharField(max_length=15, null=True, verbose_name='Código Cliente')),
                ('cliente_nome', models.CharField(max_length=80, null=True, verbose_name='Nome Cliente')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
            ],
            options={
                'unique_together': {('artigo_cod', 'designacao')},
            },
        ),
        migrations.CreateModel(
            name='ArtigoSpecsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_des', models.CharField(max_length=100, null=True, verbose_name='Designação do Item')),
                ('item_values', models.JSONField(null=True, verbose_name='Valores do Item')),
                ('item_key', models.CharField(max_length=100, null=True, verbose_name='Chave do Item')),
                ('artigospecs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.artigospecs', verbose_name='Características Técnicas')),
            ],
        ),
    ]
