# Generated by Django 3.2.8 on 2021-11-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0034_artigospecs_artigospecsitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigospecsitems',
            name='item_nvalues',
            field=models.SmallIntegerField(default=1, verbose_name='Nº de Valores'),
        ),
    ]
