# Generated by Django 3.2.8 on 2021-11-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0035_artigospecsitems_item_nvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='artigospecs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.artigospecs', verbose_name='Especificações do Artigo'),
        ),
    ]
