# Generated by Django 3.2.8 on 2021-11-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0036_tempordemfabrico_artigospecs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoNonwovens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=50, null=True, verbose_name='Designação')),
                ('versao', models.SmallIntegerField(default=1, verbose_name='Versão')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Produto Acabado')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('nw_cod_sup', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Matéria Prima (NONWOVEN)')),
                ('nw_des_sup', models.CharField(max_length=100, null=True, verbose_name='SAGE ITMDES1_0 Designação Matéria Prima (NONWOVEN)')),
                ('nw_cod_inf', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Matéria Prima (NONWOVEN)')),
                ('nw_des_inf', models.CharField(max_length=100, null=True, verbose_name='SAGE ITMDES1_0 Designação Matéria Prima (NONWOVEN)')),
            ],
            options={
                'unique_together': {('artigo_cod', 'designacao')},
            },
        ),
    ]
