# Generated by Django 3.2.8 on 2021-11-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0037_artigononwovens'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='nonwovens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.artigononwovens', verbose_name='Nonwovens'),
        ),
    ]
