# Generated by Django 3.2.8 on 2021-11-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0038_tempordemfabrico_nonwovens'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempordemfabrico',
            unique_together={('of_id', 'item_cod')},
        ),
    ]
