# Generated by Django 3.2.8 on 2021-11-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0039_alter_tempordemfabrico_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempordemfabrico',
            unique_together={('of_id', 'item_cod', 'cliente_cod', 'order_cod')},
        ),
    ]
