# Generated by Django 3.2.8 on 2021-11-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0040_alter_tempordemfabrico_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempordemfabrico',
            unique_together=set(),
        ),
    ]
