# Generated by Django 3.2.8 on 2021-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0044_paletizacao_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paletizacao',
            name='cliente_cod',
            field=models.PositiveIntegerField(null=True, verbose_name='SAGE BPCORD_0 Código de cliente'),
        ),
    ]
