# Generated by Django 3.2.8 on 2021-11-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0045_alter_paletizacao_cliente_cod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempordemfabrico',
            unique_together={('of_id', 'item_cod')},
        ),
    ]
