# Generated by Django 3.2.8 on 2021-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0047_auto_20211118_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacao',
            name='cliente_cod',
            field=models.CharField(max_length=15, null=True, verbose_name='Código Cliente'),
        ),
        migrations.AddField(
            model_name='formulacao',
            name='cliente_nome',
            field=models.CharField(max_length=80, null=True, verbose_name='Nome Cliente'),
        ),
    ]
