# Generated by Django 3.2.8 on 2021-11-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0048_auto_20211119_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='artigospecs',
        ),
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='core_cod',
        ),
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='core_des',
        ),
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='formulacao',
        ),
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='gamaoperatoria',
        ),
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='nonwovens',
        ),
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='paletizacao',
        ),
        migrations.CreateModel(
            name='TempAggOrdemFabrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_cod', models.CharField(max_length=25, null=True, verbose_name='SAGE ITMREF_0 Código Matéria Prima (CORE)')),
                ('core_des', models.CharField(max_length=100, null=True, verbose_name='SAGE ITMDES1_0 Designação Matéria Prima (CORE)')),
                ('artigospecs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.artigospecs', verbose_name='Especificações do Artigo')),
                ('formulacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.formulacao', verbose_name='Formulação')),
                ('gamaoperatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.gamaoperatoria', verbose_name='Gama Operatória')),
                ('nonwovens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.artigononwovens', verbose_name='Nonwovens')),
                ('paletizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.paletizacao', verbose_name='Paletização')),
            ],
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='agg_ofid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.tempaggordemfabrico', verbose_name='Aggregate Ordem de Fabrico'),
        ),
    ]
