# Generated by Django 3.2.8 on 2021-11-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0049_auto_20211120_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempordemfabrico',
            old_name='agg_ofid',
            new_name='agg_of',
        ),
    ]
