# Generated by Django 3.2.8 on 2021-11-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0050_rename_agg_ofid_tempordemfabrico_agg_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempaggordemfabrico',
            name='paletizacao',
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='paletizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.paletizacao', verbose_name='Paletização'),
        ),
    ]
