# Generated by Django 3.2.8 on 2021-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0051_auto_20211120_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='year',
            field=models.SmallIntegerField(default=2021, verbose_name='Ano'),
        ),
    ]
