# Generated by Django 3.2.8 on 2021-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0052_tempaggordemfabrico_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempaggordemfabrico',
            name='year',
            field=models.IntegerField(default=2021, verbose_name='Ano'),
        ),
    ]
