# Generated by Django 3.2.8 on 2021-11-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0053_alter_tempaggordemfabrico_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='cod',
            field=models.CharField(default='', max_length=25, verbose_name='Código Agg'),
            preserve_default=False,
        ),
    ]
