# Generated by Django 3.2.8 on 2021-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0054_tempaggordemfabrico_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='Status'),
        ),
    ]
