# Generated by Django 3.2.8 on 2021-11-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0055_tempaggordemfabrico_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_cod', models.CharField(max_length=80, verbose_name='Código Produto')),
            ],
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.produtos', verbose_name='Id Produto'),
            preserve_default=False,
        ),
    ]
