# Generated by Django 3.2.8 on 2021-11-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0060_alter_artigo_produto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='produto_id',
        ),
    ]
