# Generated by Django 3.2.8 on 2021-11-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0062_artigo_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigononwovens',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.produtos', verbose_name='Id Produto'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='artigononwovens',
            unique_together={('produto_id', 'designacao')},
        ),
        migrations.RemoveField(
            model_name='artigononwovens',
            name='artigo_cod',
        ),
    ]
