# Generated by Django 3.2.8 on 2021-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0066_auto_20211122_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='of_id',
            field=models.CharField(max_length=25, null=True, verbose_name='Ordem de Produção'),
        ),
    ]
