# Generated by Django 3.2.8 on 2021-11-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0068_auto_20211122_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cortes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.SmallIntegerField(default=1, verbose_name='Versão')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
            ],
        ),
        migrations.CreateModel(
            name='CortesArtigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Produto Acabado')),
                ('ordem', models.SmallIntegerField(verbose_name='Ordem')),
                ('largura', models.SmallIntegerField(null=True, verbose_name='Largura')),
                ('cortes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.cortes', verbose_name='Cortes')),
            ],
        ),
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='cortes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.cortes', verbose_name='Cortes'),
        ),
    ]
