# Generated by Django 3.2.8 on 2021-11-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0069_auto_20211122_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortes',
            name='largura_cod',
            field=models.CharField(default='', max_length=25, verbose_name='Código de larguras'),
            preserve_default=False,
        ),
    ]
