# Generated by Django 3.2.8 on 2021-11-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0070_cortes_largura_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortesartigos',
            name='ordem',
        ),
        migrations.AddField(
            model_name='cortesartigos',
            name='of_id',
            field=models.CharField(max_length=25, null=True, verbose_name='Ordem de Produção'),
        ),
    ]
