# Generated by Django 3.2.8 on 2021-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0071_auto_20211125_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortes',
            name='versao',
        ),
        migrations.AddField(
            model_name='cortesartigos',
            name='ncortes',
            field=models.SmallIntegerField(default=0, verbose_name='Nº de Cortes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cortesartigos',
            name='largura',
            field=models.SmallIntegerField(default=0, verbose_name='Largura'),
            preserve_default=False,
        ),
    ]
