# Generated by Django 3.2.8 on 2021-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0072_auto_20211125_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortes',
            name='largura_json',
            field=models.CharField(default='', max_length=200, verbose_name='Larguras JSON'),
            preserve_default=False,
        ),
    ]
