# Generated by Django 3.2.8 on 2021-11-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0074_cortes_largura_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortes',
            name='largura_ordem',
        ),
        migrations.CreateModel(
            name='CortesOrdem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=50, null=True, verbose_name='Designação')),
                ('versao', models.SmallIntegerField(default=1, verbose_name='Versão')),
                ('largura_ordem', models.CharField(max_length=200, verbose_name='Larguras JSON')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('cortes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.cortes', verbose_name='Id dos Cortes')),
            ],
        ),
    ]
