# Generated by Django 3.2.8 on 2021-11-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0075_auto_20211128_1931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cortesordem',
            unique_together={('cortes_id', 'designacao')},
        ),
    ]
