# Generated by Django 3.2.8 on 2021-11-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0076_alter_cortesordem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortesordem',
            name='ordem_cod',
            field=models.CharField(default='', max_length=25, verbose_name='Código de Posotionamento das larguras'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cortesordem',
            unique_together={('cortes_id', 'designacao', 'ordem_cod')},
        ),
    ]
