# Generated by Django 3.2.8 on 2021-11-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0078_alter_cortesordem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='cortesordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.cortesordem', verbose_name='Posicionamento dos Cortes'),
        ),
    ]
