# Generated by Django 3.2.8 on 2021-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0079_tempaggordemfabrico_cortesordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='linear_meters',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Metros lineares'),
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='n_paletes',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Metros Quadrados por Bobine'),
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='qty_encomenda',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Quantidade da Encomenda'),
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='sqm_bobine',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Metros Quadrados por Bobine'),
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='sqm_contentor',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Metros Quadrados por Camião/Contentor'),
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='sqm_palete',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Metros Quadrados por Palete'),
        ),
    ]
