# Generated by Django 3.2.8 on 2021-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0080_auto_20211207_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='thickness',
            field=models.IntegerField(default=325, verbose_name='Espessura (Estimada/Referência) microns'),
        ),
    ]
