# Generated by Django 3.2.8 on 2021-12-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0081_artigo_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='n_voltas',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Nº Voltas'),
        ),
    ]
