# Generated by Django 3.2.8 on 2021-12-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0082_tempordemfabrico_n_voltas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='sqm_contentor',
        ),
        migrations.RemoveField(
            model_name='tempordemfabrico',
            name='sqm_palete',
        ),
        migrations.AlterField(
            model_name='tempordemfabrico',
            name='n_paletes',
            field=models.CharField(max_length=200, null=True, verbose_name='N Paletes'),
        ),
    ]
