# Generated by Django 3.2.8 on 2021-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0084_alter_tempordemfabrico_n_paletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='item_id',
            field=models.CharField(max_length=25, null=True, verbose_name='Id Artigo'),
        ),
    ]
