# Generated by Django 3.2.8 on 2021-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0085_tempordemfabrico_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempordemfabrico',
            name='item_id',
            field=models.IntegerField(null=True, verbose_name='Id Artigo'),
        ),
    ]
