# Generated by Django 3.2.8 on 2021-12-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0086_alter_tempordemfabrico_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='draft_ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.tempordemfabrico', verbose_name='Draft Ordem de Producao'),
        ),
    ]
