# Generated by Django 3.2.8 on 2022-01-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0088_formulacaomateriasprimas_mangueira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempaggordemfabrico',
            name='year',
            field=models.IntegerField(default=2022, verbose_name='Ano'),
        ),
        migrations.CreateModel(
            name='Emendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=20, null=True, verbose_name='Designação')),
                ('cliente_cod', models.PositiveIntegerField(null=True, verbose_name='SAGE BPCORD_0 Código de cliente')),
                ('cliente_nome', models.CharField(max_length=80, null=True, verbose_name='Nome Cliente')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='SAGE ITMREF_0 Código Produto Acabado')),
                ('tipo_emenda', models.CharField(max_length=35, verbose_name='Tipo Emenda')),
                ('maximo', models.SmallIntegerField(default=0, max_length=3, verbose_name='Máximo Emendas')),
                ('emendas_rolo', models.SmallIntegerField(max_length=2, verbose_name='Emendas por Rolo')),
                ('paletes_contentor', models.SmallIntegerField(max_length=2, verbose_name='Emendas Paletes por Contentor')),
            ],
            options={
                'unique_together': {('designacao', 'cliente_cod', 'artigo_cod')},
            },
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='emendas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.emendas', verbose_name='Emendas'),
        ),
    ]
