# Generated by Django 3.2.8 on 2022-01-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0090_auto_20220103_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='end_prev_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim Prevista'),
        ),
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Início'),
        ),
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='start_prev_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Início Prevista'),
        ),
    ]
