# Generated by Django 3.2.8 on 2022-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0091_auto_20220110_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='n_paletes_total',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Nº de Paletes Total'),
        ),
    ]
