# Generated by Django 3.2.8 on 2022-01-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0092_tempordemfabrico_n_paletes_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendas',
            name='hashcode',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='hashcode'),
        ),
    ]
