# Generated by Django 3.2.8 on 2022-01-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0093_emendas_hashcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='formu',
            field=models.CharField(choices=[('HE', 'HE'), ('HT', 'HT'), ('', '')], default='', max_length=10, verbose_name='Formulação'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='thickness',
            field=models.IntegerField(default=325, null=True, verbose_name='Espessura (Estimada/Referência) microns'),
        ),
    ]
