# Generated by Django 3.2.8 on 2022-01-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0094_auto_20220113_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.IntegerField(verbose_name='Tipo Documento')),
                ('path', models.TextField(default='', max_length=1000, verbose_name='Caminho')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.tempordemfabrico', verbose_name='Temporary Ordem fabrico')),
            ],
        ),
    ]
