# Generated by Django 3.2.8 on 2022-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0098_auto_20220118_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='Status'),
        ),
    ]
