# Generated by Django 3.2.8 on 2022-01-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0100_remove_tempordemfabrico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempaggordemfabrico',
            name='core_cod',
        ),
        migrations.RemoveField(
            model_name='tempaggordemfabrico',
            name='core_des',
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='core_cod',
            field=models.CharField(max_length=25, null=True, verbose_name='SAGE ITMREF_0 Código Matéria Prima (CORE)'),
        ),
        migrations.AddField(
            model_name='tempordemfabrico',
            name='core_des',
            field=models.CharField(max_length=100, null=True, verbose_name='SAGE ITMDES1_0 Designação Matéria Prima (CORE)'),
        ),
    ]
