# Generated by Django 3.2.8 on 2022-01-23 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producao', '0101_auto_20220121_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulacao', models.JSONField(blank=True, null=True)),
                ('gamaoperatoria', models.JSONField(blank=True, null=True)),
                ('nonwovens', models.JSONField(blank=True, null=True)),
                ('artigospecs', models.JSONField(blank=True, null=True)),
                ('cortes', models.JSONField(blank=True, null=True)),
                ('cortesordem', models.JSONField(blank=True, null=True)),
                ('cores', models.JSONField(blank=True, null=True)),
                ('paletizacao', models.JSONField(blank=True, null=True)),
                ('emendas', models.JSONField(blank=True, null=True)),
                ('ofs', models.JSONField(blank=True, null=True)),
                ('paletesstock', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Observações')),
                ('start_prev_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Início Prevista')),
                ('end_prev_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim Prevista')),
                ('horas_previstas_producao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Horas previstas de produção')),
                ('sentido_enrolamento', models.CharField(max_length=100, null=True, verbose_name='Sentido de Enrolamento')),
                ('amostragem', models.IntegerField(max_length=2, null=True, verbose_name='Amostragem')),
                ('agg_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.tempaggordemfabrico', verbose_name='Aggregate Ordem de Fabrico')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditCurrentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulacao', models.JSONField(blank=True, null=True)),
                ('gamaoperatoria', models.JSONField(blank=True, null=True)),
                ('nonwovens', models.JSONField(blank=True, null=True)),
                ('artigospecs', models.JSONField(blank=True, null=True)),
                ('cortes', models.JSONField(blank=True, null=True)),
                ('cortesordem', models.JSONField(blank=True, null=True)),
                ('cores', models.JSONField(blank=True, null=True)),
                ('paletizacao', models.JSONField(blank=True, null=True)),
                ('emendas', models.JSONField(blank=True, null=True)),
                ('ofs', models.JSONField(blank=True, null=True)),
                ('paletesstock', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Observações')),
                ('start_prev_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Início Prevista')),
                ('end_prev_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim Prevista')),
                ('horas_previstas_producao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Horas previstas de produção')),
                ('sentido_enrolamento', models.CharField(max_length=100, null=True, verbose_name='Sentido de Enrolamento')),
                ('amostragem', models.IntegerField(max_length=2, null=True, verbose_name='Amostragem')),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=8, null=True)),
                ('contextid', models.IntegerField(blank=True, null=True)),
                ('agg_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.tempaggordemfabrico', verbose_name='Aggregate Ordem de Fabrico')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'db_table': 'audit_currentsettings',
            },
        ),
    ]
