# Generated by Django 3.2.8 on 2022-01-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0101_auto_20220121_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDraftAggordemfabrico',
            fields=[
                ('tempaggordemfabrico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='producao.tempaggordemfabrico')),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=8, null=True)),
                ('contextid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_draft_aggordemfabrico',
            },
            bases=('producao.tempaggordemfabrico',),
        ),
    ]
