# Generated by Django 3.2.8 on 2022-01-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0102_auditdraftaggordemfabrico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditDraftAggordemfabrico',
        ),
    ]
