# Generated by Django 3.2.8 on 2022-01-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0102_auditcurrentsettings_currentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='gsm',
            field=models.IntegerField(max_length=3, null=True, verbose_name='Gramagem'),
        ),
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.produtos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='produto_cod',
            field=models.CharField(max_length=200, null=True, verbose_name='Codigo do Produto'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='gsm',
            field=models.IntegerField(max_length=3, null=True, verbose_name='Gramagem'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.produtos', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='produto_cod',
            field=models.CharField(max_length=200, null=True, verbose_name='Codigo do Produto'),
        ),
    ]
