# Generated by Django 3.2.8 on 2022-01-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0103_delete_auditdraftaggordemfabrico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDraftAggordemfabrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=25, verbose_name='Código Agg')),
                ('sentido_enrolamento', models.CharField(max_length=100, null=True, verbose_name='Sentido de Enrolamento')),
                ('amostragem', models.IntegerField(max_length=2, null=True, verbose_name='Amostragem')),
                ('observacoes', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Observações')),
                ('year', models.IntegerField(default=2022, verbose_name='Ano')),
                ('status', models.SmallIntegerField(default=0, verbose_name='Status')),
                ('start_prev_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Início Prevista')),
                ('end_prev_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim Prevista')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim')),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=8, null=True)),
                ('contextid', models.IntegerField(blank=True, null=True)),
                ('artigospecs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.artigospecs', verbose_name='Especificações do Artigo')),
                ('cortes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.cortes', verbose_name='Cortes')),
                ('cortesordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.cortesordem', verbose_name='Posicionamento dos Cortes')),
                ('formulacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.formulacao', verbose_name='Formulação')),
                ('gamaoperatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.gamaoperatoria', verbose_name='Gama Operatória')),
                ('nonwovens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.artigononwovens', verbose_name='Nonwovens')),
            ],
            options={
                'db_table': 'audit_draft_aggordemfabrico',
            },
        ),
    ]
