# Generated by Django 3.2.8 on 2022-01-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0104_auditdraftaggordemfabrico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulacao', models.JSONField(blank=True, null=True)),
                ('gamaoperatoria', models.JSONField(blank=True, null=True)),
                ('nonwovens', models.JSONField(blank=True, null=True)),
                ('artigospecs', models.JSONField(blank=True, null=True)),
                ('cortes', models.JSONField(blank=True, null=True)),
                ('cortesordem', models.JSONField(blank=True, null=True)),
                ('cores', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0, verbose_name='Status')),
                ('agg_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.tempaggordemfabrico', verbose_name='Aggregate Ordem de Fabrico')),
            ],
        ),
    ]
