# Generated by Django 3.2.8 on 2022-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0104_auto_20220129_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditcurrentsettings',
            old_name='type',
            new_name='type_op',
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='type_op',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
