# Generated by Django 3.2.8 on 2022-01-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0105_currentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsettings',
            name='emendas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='ofs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='paletizacao',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
