# Generated by Django 4.0.2 on 2022-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0108_currentsettings_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentsettings',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
