# Generated by Django 4.0.2 on 2022-02-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0109_rename_timestamp_currentsettings_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='limites',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='limites',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
