# Generated by Django 4.0.2 on 2022-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0110_auditcurrentsettings_limites_currentsettings_limites'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletizacao',
            name='folha_identificativa',
            field=models.SmallIntegerField(default=0, verbose_name='Folha Identificativa de Palete'),
        ),
    ]
