# Generated by Django 4.0.2 on 2022-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0111_paletizacao_folha_identificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletizacao',
            name='versao',
            field=models.SmallIntegerField(default=1, verbose_name='Versão'),
        ),
    ]
