# Generated by Django 4.0.2 on 2022-02-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0112_paletizacao_versao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='aggregated',
            field=models.SmallIntegerField(default=0, verbose_name='Ordem de Fabrico agregada (0/1)'),
        ),
    ]
