# Generated by Django 4.0.2 on 2022-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0113_tempordemfabrico_aggregated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='horas_previstas_producao',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Horas previstas de produção'),
        ),
    ]
