# Generated by Django 4.0.2 on 2022-02-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0114_tempaggordemfabrico_horas_previstas_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortes',
            name='largura_util',
            field=models.SmallIntegerField(null=True, verbose_name='Largura Útil'),
        ),
    ]
