# Generated by Django 4.0.2 on 2022-02-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0115_cortes_largura_util'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempaggordemfabrico',
            name='horas_previstas_producao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Horas previstas de produção'),
        ),
    ]
