# Generated by Django 4.0.2 on 2022-03-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0116_alter_tempaggordemfabrico_horas_previstas_producao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CortesArtigos',
        ),
    ]
