# Generated by Django 4.0.2 on 2022-03-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0117_delete_cortesartigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CortesArtigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.CharField(max_length=400, verbose_name='OFS JSON')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('cortes_ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.cortesordem', verbose_name='Cortes')),
            ],
        ),
    ]
