# Generated by Django 4.0.2 on 2022-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0118_cortesartigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='ofs_ordem',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='ofs_ordem',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CortesArtigos',
        ),
    ]
