# Generated by Django 4.0.2 on 2022-03-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0119_auditcurrentsettings_ofs_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinagem',
            name='audit_current_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.auditcurrentsettings', verbose_name='Audit Current Settings'),
        ),
    ]
