# Generated by Django 4.0.2 on 2022-03-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0120_bobinagem_audit_current_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinagem',
            name='valid',
            field=models.SmallIntegerField(default=1, verbose_name='Bobinagem Validada'),
        ),
    ]
