# Generated by Django 4.0.2 on 2022-03-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0121_bobinagem_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobinagemConsumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_bobinagem_id', models.IntegerField(null=True, verbose_name='Id IG BOBINAGEM')),
                ('A1', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='A1')),
                ('A2', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='A2')),
                ('A3', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='A3')),
                ('A4', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='A4')),
                ('A5', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='A5')),
                ('A6', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='A6')),
                ('B1', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='B1')),
                ('B2', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='B2')),
                ('B3', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='B3')),
                ('B4', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='B4')),
                ('B5', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='B5')),
                ('B6', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='B6')),
                ('C1', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='C1')),
                ('C2', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='C2')),
                ('C3', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='C3')),
                ('C4', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='C4')),
                ('C5', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='C5')),
                ('C6', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='C6')),
                ('metros', models.IntegerField(null=True, verbose_name='Metros')),
                ('nw_inf', models.IntegerField(null=True, verbose_name='Id IG BOBINAGEM')),
                ('nw_sup', models.IntegerField(null=True, verbose_name='Id IG BOBINAGEM')),
                ('peso', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Peso')),
                ('diametro', models.DecimalField(decimal_places=5, max_digits=12, null=True, verbose_name='Diametro')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data Início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim')),
                ('bobinagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.bobinagem', verbose_name='Bobinagem')),
            ],
        ),
    ]
