# Generated by Django 4.0.2 on 2022-04-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0122_bobinagemconsumos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotesDosers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_lote', models.CharField(max_length=100, verbose_name='Nº Lote')),
                ('doser', models.CharField(max_length=2, verbose_name='Doseadora')),
                ('artigo_cod', models.CharField(max_length=25, verbose_name='Código Artigo')),
                ('qty', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Quantidade Total do Lote')),
                ('qty_cons', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Quantidade atual (igual à qty cons, ou seja, consumida durante produção, é este o valor a ter em consideração, no entanto este valor pode ser ajustado manualmente )')),
                ('status', models.SmallIntegerField(default=0, verbose_name='Status')),
                ('t_stamp', models.DateTimeField()),
                ('audit_cs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.auditcurrentsettings', verbose_name='Audit Current Settings')),
                ('formulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.formulacao', verbose_name='Formulação')),
            ],
        ),
    ]
