# Generated by Django 4.0.2 on 2022-04-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0123_lotesdosers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, verbose_name='Código')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('status', models.SmallIntegerField(default=0, verbose_name='Status')),
            ],
        ),
    ]
