# Generated by Django 4.0.2 on 2022-04-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0124_qrcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesdosers',
            name='item_id',
            field=models.IntegerField(null=True, verbose_name='Item ID'),
        ),
    ]
