# Generated by Django 4.0.2 on 2022-04-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0125_lotesdosers_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesdosers',
            name='cs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producao.currentsettings', verbose_name='Current Settings'),
            preserve_default=False,
        ),
    ]
