# Generated by Django 4.0.2 on 2022-04-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0129_lotesdosers_ig_bobinagem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesdosers',
            name='type_mov',
            field=models.CharField(default='IN', max_length=4, verbose_name='Tipo de Movimento'),
            preserve_default=False,
        ),
    ]
