# Generated by Django 4.0.2 on 2022-04-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0132_remove_lotesdosers_qty_acum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesdosers',
            name='qty_total_lote',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True, verbose_name='Quantidade Total do Lote'),
        ),
        migrations.AlterField(
            model_name='lotesdosers',
            name='qty_lote',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True, verbose_name='Quantidade Total do Lote por doseador'),
        ),
    ]
