# Generated by Django 4.0.2 on 2022-05-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0133_lotesdosers_qty_total_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinagem',
            name='ig_bobinagem_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='IG_BOBINAGEM'),
        ),
        migrations.CreateModel(
            name='LotesLinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_lote', models.CharField(max_length=100, null=True, verbose_name='Nº Lote')),
                ('artigo_cod', models.CharField(max_length=25, null=True, verbose_name='Código Artigo')),
                ('qty_lote', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True, verbose_name='Quantidade Total do Lote')),
                ('qty_doser', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True, verbose_name='Quantidade consumida no doseador (consumida durante a produção)')),
                ('qty_consumed', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True, verbose_name='Quantidade consumida (consumida durante a produção)')),
                ('qty_acumulated', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True, verbose_name='Quantidade Acumulada')),
                ('qty_rest', models.DecimalField(decimal_places=5, default=0, max_digits=12, null=True, verbose_name='Quantidade Acumulada Anterior )')),
                ('status', models.SmallIntegerField(default=0, verbose_name='Status')),
                ('type_mov', models.CharField(max_length=4, verbose_name='Tipo de Movimento')),
                ('item_id', models.IntegerField(null=True, verbose_name='Item ID')),
                ('t_stamp', models.DateTimeField()),
                ('ig_bobinagem_id', models.IntegerField(null=True, verbose_name='Id IG BOBINAGEM')),
                ('audit_cs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.auditcurrentsettings', verbose_name='Audit Current Settings')),
                ('cs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.currentsettings', verbose_name='Current Settings')),
                ('formulacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.formulacao', verbose_name='Formulação')),
            ],
        ),
    ]
