# Generated by Django 4.0.2 on 2022-05-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0134_bobinagem_ig_bobinagem_id_loteslinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobinagem',
            name='tiponwinf',
            field=models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici'), ('Fitesa', 'Fitesa'), ('ALBIS 23', 'ALBIS 23'), ('ALBIS 16', 'ALBIS 16'), ('Union Pillow', 'Union Pillow'), ('Union UV', 'Union UV'), ('Jacob Holm', 'Jacob Holm'), ('Nonwoven Nikoo 25gsm Spunlace 100PP', 'Nonwoven Nikoo 25gsm Spunlace 100PP'), ('ELA-ACE', 'ELA-ACE'), ('ELA-SPUN', 'ELA-SPUN'), ('Nonwoven Nikoo 28gsm Spunlace 100PP', 'Nonwoven Nikoo 28gsm Spunlace 100PP'), ('NW Vaporjet 25gsm Spunlace 100PP 2200', 'NW Vaporjet 25gsm Spunlace 100PP 2200'), ('Sandler Sawabond 7059 24gsm', 'Sandler Sawabond 7059 24gsm'), ('Nonwoven ANT - ANTJET 25gsm 100PP 2200', 'Nonwoven ANT - ANTJET 25gsm 100PP 2200'), ('Sandler 16gsm Sawabond 100PP 2200', 'Sandler 16gsm Sawabond 100PP 2200'), ('Teksis 52160EL 16gsm L2200', 'Teksis 52160EL 16gsm L2200'), ('Union KB1600PHW 16gsm L2200', 'Union KB1600PHW 16gsm L2200')], default='', max_length=200, null=True, verbose_name='Tipo Nonwoven Inferior'),
        ),
        migrations.AlterField(
            model_name='bobinagem',
            name='tiponwsup',
            field=models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici'), ('Fitesa', 'Fitesa'), ('ALBIS 23', 'ALBIS 23'), ('ALBIS 16', 'ALBIS 16'), ('Union Pillow', 'Union Pillow'), ('Union UV', 'Union UV'), ('Jacob Holm', 'Jacob Holm'), ('Nonwoven Nikoo 25gsm Spunlace 100PP', 'Nonwoven Nikoo 25gsm Spunlace 100PP'), ('ELA-ACE', 'ELA-ACE'), ('ELA-SPUN', 'ELA-SPUN'), ('Nonwoven Nikoo 28gsm Spunlace 100PP', 'Nonwoven Nikoo 28gsm Spunlace 100PP'), ('NW Vaporjet 25gsm Spunlace 100PP 2200', 'NW Vaporjet 25gsm Spunlace 100PP 2200'), ('Sandler Sawabond 7059 24gsm', 'Sandler Sawabond 7059 24gsm'), ('Nonwoven ANT - ANTJET 25gsm 100PP 2200', 'Nonwoven ANT - ANTJET 25gsm 100PP 2200'), ('Sandler 16gsm Sawabond 100PP 2200', 'Sandler 16gsm Sawabond 100PP 2200'), ('Teksis 52160EL 16gsm L2200', 'Teksis 52160EL 16gsm L2200'), ('Union KB1600PHW 16gsm L2200', 'Union KB1600PHW 16gsm L2200')], default='', max_length=200, null=True, verbose_name='Tipo Nonwoven Superior'),
        ),
    ]
