# Generated by Django 4.0.2 on 2022-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0135_alter_bobinagem_tiponwinf_alter_bobinagem_tiponwsup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesdosers',
            name='t_stamp_fix',
            field=models.DateTimeField(null=True),
        ),
    ]
