# Generated by Django 4.0.2 on 2022-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0136_lotesdosers_t_stamp_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesdosers',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Ordem principal'),
        ),
        migrations.AddField(
            model_name='lotesdosers',
            name='sub_order',
            field=models.IntegerField(null=True, verbose_name='sub Ordem'),
        ),
    ]
