# Generated by Django 4.0.2 on 2022-06-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0137_lotesdosers_order_lotesdosers_sub_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='produto_alt',
            field=models.CharField(max_length=200, null=True, verbose_name='Designação de Produto Alternativo'),
        ),
    ]
