# Generated by Django 4.0.2 on 2022-08-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0138_tempordemfabrico_produto_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciclado',
            name='status',
            field=models.PositiveIntegerField(default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='produto_id',
            field=models.ForeignKey(blank=True, db_column='produto_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.produtos', verbose_name='Id Produto'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='thickness',
            field=models.IntegerField(blank=True, default=325, null=True, verbose_name='Espessura (Estimada/Referência) microns'),
        ),
    ]
