# Generated by Django 4.0.2 on 2022-08-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0140_recicladolotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecicladoLotes',
        ),
    ]
