# Generated by Django 4.0.2 on 2022-08-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0144_artigocliente_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='buracos_pos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bobine',
            name='fc_pos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bobine',
            name='ff_pos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bobine',
            name='furos_pos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
