# Generated by Django 4.0.2 on 2022-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0145_bobine_buracos_pos_bobine_fc_pos_bobine_ff_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinagem',
            name='largura_bruta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Largura Bruta'),
        ),
    ]
