# Generated by Django 4.0.2 on 2022-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0147_alter_bobinagem_largura_bruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='rugas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Rugas'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='rugas_pos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bobine',
            name='tr',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Troca Rápida'),
        ),
    ]
