# Generated by Django 4.0.2 on 2022-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0148_bobine_rugas_bobine_rugas_pos_bobine_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='ordem_id_original',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordem ID Original'),
        ),
    ]
