# Generated by Django 4.0.2 on 2022-09-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0149_palete_ordem_id_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='ordem_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordem ID Original'),
        ),
    ]
