# Generated by Django 4.0.2 on 2022-10-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0150_bobine_ordem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Início'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Início'),
        ),
    ]
