# Generated by Django 4.0.2 on 2022-10-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0151_auditcurrentsettings_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinagem',
            name='valid_tsamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Validação'),
        ),
    ]
