# Generated by Django 4.0.2 on 2022-10-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0152_bobinagem_valid_tsamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobinagem',
            old_name='valid_tsamp',
            new_name='valid_tstamp',
        ),
    ]
