# Generated by Django 4.0.2 on 2022-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0154_auditcurrentsettings_ignore_audit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='formulacaov2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='formulacaov2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
