# Generated by Django 4.0.2 on 2022-10-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0155_auditcurrentsettings_formulacaov2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='ordem_changed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indica se a ordem foi alterada após primeira atribuição'),
        ),
    ]
