# Generated by Django 4.0.2 on 2022-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0156_bobine_ordem_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='core',
            field=models.IntegerField(blank=True, null=True, verbose_name='Core'),
        )
    ]
