# Generated by Django 4.0.2 on 2022-10-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0157_bobine_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='lar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Core'),
        )
    ]
