# Generated by Django 4.0.2 on 2022-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0158_bobine_lar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='lotenwinf',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lote Nonwoven Inferior'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='lotenwsup',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lote Nonwoven Superior'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='nwinf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo Nonwoven Inferior'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='nwsup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consumo Nonwoven Superior'),
        ),
    ]
