# Generated by Django 4.0.2 on 2022-10-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0159_bobine_lotenwinf_bobine_lotenwsup_bobine_nwinf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='acs_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Settings applyed '),
        ),
        migrations.AddField(
            model_name='bobine',
            name='agg_of_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aggregated OF'),
        ),
    ]
