# Generated by Django 4.0.2 on 2022-10-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0160_bobine_acs_id_bobine_agg_of_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='ignore_audit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ignore Audit'),
        ),
    ]
