# Generated by Django 4.0.2 on 2022-12-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0162_alter_formulacao_designacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamaoperatoria',
            name='designacao',
            field=models.CharField(max_length=80, null=True, verbose_name='Designação'),
        ),
    ]
