# Generated by Django 4.0.2 on 2022-12-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0164_palete_ignore_audit_palete_nbobines'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='area_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Área palete'),
        ),
        migrations.AddField(
            model_name='palete',
            name='comp_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento palete'),
        ),
        migrations.AddField(
            model_name='palete',
            name='diam_avg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Diametro AVG palete'),
        ),
        migrations.AddField(
            model_name='palete',
            name='diam_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Diametro Maximo palete'),
        ),
        migrations.AddField(
            model_name='palete',
            name='diam_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Diametro Minimo palete'),
        ),
        migrations.AddField(
            model_name='palete',
            name='nbobines_real',
            field=models.IntegerField(null=True, verbose_name='Bobines total'),
        ),
    ]
