# Generated by Django 4.0.2 on 2022-12-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0165_palete_area_real_palete_comp_real_palete_diam_avg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palete',
            name='nbobines',
        ),
    ]
