# Generated by Django 4.0.2 on 2022-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0167_palete_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='artigo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
