# Generated by Django 4.0.2 on 2023-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0168_palete_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='paletizacao',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempaggordemfabrico',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Ano'),
        ),
    ]
