# Generated by Django 4.0.2 on 2023-01-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0170_palete_destinos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='destinos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
