# Generated by Django 4.0.2 on 2023-01-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0171_bobine_destinos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='ig_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ig_id'),
        ),
    ]
