# Generated by Django 4.0.2 on 2023-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0172_bobine_ig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='nbobines_emendas',
            field=models.IntegerField(null=True, verbose_name='Bobines Com emendas'),
        ),
    ]
