# Generated by Django 4.0.2 on 2023-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0174_bobine_destinos_has_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='destinos_has_obs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indica se os destinos têm observações'),
        ),
    ]
