# Generated by Django 4.0.2 on 2023-01-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0175_palete_destinos_has_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='typeofabrico',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Tipo de Ordem de Fabrico'),
        ),
    ]
