# Generated by Django 4.0.2 on 2023-01-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0176_tempordemfabrico_typeofabrico'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinagem',
            name='vcr_num_inf',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Vcr inf'),
        ),
        migrations.AddField(
            model_name='bobinagem',
            name='vcr_num_sup',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Vcr sup'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='vcr_num_inf',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Vcr inf'),
        ),
        migrations.AddField(
            model_name='bobine',
            name='vcr_num_sup',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Vcr sup'),
        ),
    ]
