# Generated by Django 4.0.2 on 2023-02-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0177_bobinagem_vcr_num_inf_bobinagem_vcr_num_sup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='troca_etiqueta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Troca de Etiqueta'),
        ),
    ]
