# Generated by Django 4.0.2 on 2023-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0179_bobine_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emenda',
            name='bobinagem_original_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bobinagem Original em caso de clone'),
        ),
        migrations.AddField(
            model_name='emenda',
            name='troca_etiqueta',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Indica se foi troca de eqiqueta'),
        ),
    ]
