# Generated by Django 4.0.2 on 2023-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0180_emenda_bobinagem_original_id_emenda_troca_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacao',
            name='group_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='formulacao',
            name='reference',
            field=models.SmallIntegerField(default=1, verbose_name='Referência'),
        ),
        migrations.AddField(
            model_name='formulacao',
            name='subgroup_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Subgroup'),
        ),
    ]
