# Generated by Django 4.0.2 on 2023-04-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0181_formulacao_group_name_formulacao_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacao',
            name='artigo_id',
            field=models.SmallIntegerField(null=True, verbose_name='Artigo'),
        ),
    ]
