# Generated by Django 4.0.2 on 2023-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0182_formulacao_artigo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='lvl',
            field=models.IntegerField(null=True, verbose_name='Indica a posição no embalamento'),
        ),
        migrations.AddField(
            model_name='palete',
            name='lvl_item_id',
            field=models.IntegerField(null=True, verbose_name='Indica o id do item no embalamento'),
        ),
    ]
