# Generated by Django 4.0.2 on 2023-05-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0183_palete_lvl_palete_lvl_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paletizacao',
            name='designacao',
            field=models.CharField(max_length=30, null=True, verbose_name='Designação'),
        ),
    ]
