# Generated by Django 4.0.2 on 2023-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0185_alter_artigo_des_alter_artigo_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='nbobines_sem_destino',
            field=models.IntegerField(null=True, verbose_name='Indica o numero de bobines sem destino em estado DM'),
        ),
    ]
