# Generated by Django 4.0.2 on 2023-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0187_bobine_cliente_cod_bobine_cliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='nok',
            field=models.IntegerField(null=True, verbose_name='em conjugação com nok_estados mais o nº de bobines(se corresponde ao nbones defindo)'),
        ),
        migrations.AddField(
            model_name='palete',
            name='nok_estados',
            field=models.IntegerField(null=True, verbose_name='Indica se as bobines da palete de produto acabado estão apenas em LAB e G se sim nok=0 senão nok=1'),
        ),
    ]
