# Generated by Django 4.0.2 on 2023-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0188_palete_nok_palete_nok_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetapalete',
            name='bobines',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
