# Generated by Django 4.0.2 on 2023-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0189_etiquetapalete_bobines'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='cortes_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
