# Generated by Django 4.0.2 on 2023-07-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0191_tempaggordemfabrico_nws_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='cortes_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='nws_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='cortes_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='nws_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
