# Generated by Django 4.0.2 on 2023-07-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0192_auditcurrentsettings_cortes_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetapalete',
            name='to_sign',
            field=models.IntegerField(blank=True, null=True, verbose_name='Assinar'),
        ),
    ]
