# Generated by Django 4.0.2 on 2023-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0193_etiquetapalete_to_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='formulacao_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
