# Generated by Django 4.0.2 on 2023-07-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0195_auditcurrentsettings_formulacao_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempaggordemfabrico',
            name='formulacao_plan',
        ),
        migrations.RemoveField(
            model_name='tempaggordemfabrico',
            name='nws_plan',
        ),
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='formulacao_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de formulações'),
        ),
    ]
