# Generated by Django 4.0.2 on 2023-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0196_remove_tempaggordemfabrico_formulacao_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='formulacao_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de formulações'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='formulacao_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de formulações'),
        ),
    ]
