# Generated by Django 4.0.2 on 2023-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0197_auditcurrentsettings_formulacao_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacao',
            name='joinbc',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Join extrusora BC'),
        ),
    ]
