# Generated by Django 4.0.2 on 2023-08-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0198_formulacao_joinbc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulacao',
            name='joinbc',
            field=models.SmallIntegerField(default=1, null=True, verbose_name='Join extrusora BC'),
        ),
    ]
