# Generated by Django 4.0.2 on 2023-08-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0199_alter_formulacao_joinbc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditcurrentsettings',
            name='cortes_plan',
        ),
        migrations.RemoveField(
            model_name='auditcurrentsettings',
            name='formulacao_plan',
        ),
        migrations.RemoveField(
            model_name='auditcurrentsettings',
            name='nws_plan',
        ),
        migrations.RemoveField(
            model_name='currentsettings',
            name='cortes_plan',
        ),
        migrations.RemoveField(
            model_name='currentsettings',
            name='formulacao_plan',
        ),
        migrations.RemoveField(
            model_name='currentsettings',
            name='nws_plan',
        ),
    ]
