# Generated by Django 4.0.2 on 2023-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0200_remove_auditcurrentsettings_cortes_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempaggordemfabrico',
            name='cortes_plan',
        ),
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='cortes_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de cortes'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='cortes_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de cortes'),
        ),
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='cortes_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de Cortes'),
        ),
    ]
