# Generated by Django 4.0.2 on 2023-08-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0201_remove_tempaggordemfabrico_cortes_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='item_lar',
            field=models.IntegerField(null=True, verbose_name='Largura do artigo, aplica-se caso o artigo seja do tipo amostra (na tabela artigos é 0)'),
        ),
    ]
