# Generated by Django 4.0.2 on 2023-08-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0202_tempordemfabrico_item_lar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='certificacoes',
            field=models.CharField(max_length=200, null=True, verbose_name='Certificações'),
        ),
    ]
