# Generated by Django 4.0.2 on 2023-08-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0203_artigo_certificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempordemfabrico',
            name='certificacoes',
            field=models.CharField(max_length=200, null=True, verbose_name='Certificações'),
        ),
    ]
