# Generated by Django 4.0.2 on 2023-08-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0204_tempordemfabrico_certificacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='certificacoes',
        ),
    ]
