# Generated by Django 4.0.2 on 2023-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0205_remove_artigo_certificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='reported',
            field=models.IntegerField(null=True, verbose_name='Indica se a palete foi sincronizada com o SAGE'),
        ),
    ]
