# Generated by Django 4.0.2 on 2023-09-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0206_palete_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='nw_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de Nonwovens'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='nw_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de Nonwovens'),
        ),
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='nw_plan_id',
            field=models.IntegerField(null=True, verbose_name='Plano de Nonwovens'),
        ),
    ]
