# Generated by Django 4.0.2 on 2023-09-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0207_auditcurrentsettings_nw_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciclado',
            name='reported',
            field=models.IntegerField(null=True, verbose_name='Indica se o reciclado foi sincronizado com o SAGE'),
        ),
    ]
