# Generated by Django 4.0.2 on 2023-10-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0208_reciclado_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='eef',
            field=models.CharField(max_length=17, null=True, verbose_name='Encomenda'),
        ),
    ]
