# Generated by Django 4.0.2 on 2023-10-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0209_carga_eef'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='artigos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
