# Generated by Django 4.0.2 on 2023-10-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0210_carga_artigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='prf',
            field=models.CharField(max_length=17, null=True, verbose_name='prf'),
        ),
    ]
