# Generated by Django 4.0.2 on 2023-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0211_carga_prf'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='cliente',
            field=models.CharField(max_length=255, null=True, verbose_name='cliente'),
        ),
    ]
