# Generated by Django 4.0.2 on 2023-11-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0215_attachments_tipo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcurrentsettings',
            name='cortes_test',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='cortes_test',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempaggordemfabrico',
            name='cortes_test',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
