# Generated by Django 4.0.2 on 2024-03-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0219_bobine_mpalete_bobine_rasgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletizacaodetails',
            name='item_cintas',
            field=models.SmallIntegerField(default=0, verbose_name='Item Ordem'),
            preserve_default=False,
        ),
    ]
