# Generated by Django 4.0.2 on 2024-03-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0221_paletizacao_artigo_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palete',
            name='bobines_schema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bobines Schema'),
        ),
        migrations.AddField(
            model_name='palete',
            name='paletizacao_id',
            field=models.IntegerField(null=True, verbose_name='Paletização Id'),
        ),
    ]
