# Generated by Django 4.0.2 on 2024-03-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0222_palete_bobines_schema_palete_paletizacao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletizacao',
            name='sentido_desenrolamento',
            field=models.CharField(default='Direita', max_length=12, null=True, verbose_name='Sentido desenrolamento'),
        ),
    ]
