# Generated by Django 4.0.2 on 2024-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0223_paletizacao_sentido_desenrolamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletizacaodetails',
            name='item_size',
            field=models.CharField(max_length=20, null=True, verbose_name='Item Tamanho'),
        ),
    ]
