# Generated by Django 4.0.2 on 2024-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0224_paletizacaodetails_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='cliente_cod',
            field=models.IntegerField(null=True, verbose_name='Cod Cliente'),
        ),
    ]
