# Generated by Django 4.0.2 on 2024-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0225_carga_cliente_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='matricula',
            field=models.CharField(max_length=100, null=True, verbose_name='Matricula'),
        ),
        migrations.AddField(
            model_name='carga',
            name='matricula_reboque',
            field=models.CharField(max_length=100, null=True, verbose_name='Matricula Reboque'),
        ),
        migrations.AddField(
            model_name='carga',
            name='modo_exp',
            field=models.CharField(max_length=100, null=True, verbose_name='Modo Expedição'),
        ),
    ]
