# Generated by Django 4.0.2 on 2024-03-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0226_carga_matricula_carga_matricula_reboque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='data_producao',
            field=models.IntegerField(null=True, verbose_name='Com ou sem data de produção'),
        ),
        migrations.AddField(
            model_name='carga',
            name='po_cliente',
            field=models.CharField(max_length=100, null=True, verbose_name='PO Cliente'),
        ),
    ]
