# Generated by Django 3.2.8 on 2021-10-16 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasTecnicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Caracteristicas Técnicas',
            },
        ),
        migrations.CreateModel(
            name='CTInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Basis weight (gsm)')),
                ('tensile_peak', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tensile at peak CD (N/25mm)')),
                ('elong_break_cd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Elongation at break CD (%)')),
                ('elong_n_cd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Elongation at 9.81N CD (%)')),
                ('load_five', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 5% elongation 1st cycle CD (N/50 mm)')),
                ('load_ten', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 10% elongation 1st cycle CD (N/50 mm)')),
                ('load_twenty', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 20% elongation 1st cycle CD (N/50 mm)')),
                ('load_fifty', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 50% elongation 1st cycle CD (N/50 mm)')),
                ('perm_set_second', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Permanent set 2nd cycle (%)')),
                ('load_hundred_second', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 100% elongation 2nd cycle (N/50 mm)')),
                ('perm_set_third', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Permanent set 3rd cycle (%)')),
                ('load_hundred_third', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 100% elongation 3rd cycle (N/50 mm)')),
                ('lamination_str', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lamination strenght (CD) (N/25 mm)')),
            ],
            options={
                'verbose_name_plural': 'CTInfs',
            },
        ),
        migrations.CreateModel(
            name='CTSup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Basis weight (gsm)')),
                ('tensile_peak', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tensile at peak CD (N/25mm)')),
                ('elong_break_cd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Elongation at break CD (%)')),
                ('elong_n_cd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Elongation at 9.81N CD (%)')),
                ('load_five', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 5% elongation 1st cycle CD (N/50 mm)')),
                ('load_ten', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 10% elongation 1st cycle CD (N/50 mm)')),
                ('load_twenty', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 20% elongation 1st cycle CD (N/50 mm)')),
                ('load_fifty', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 50% elongation 1st cycle CD (N/50 mm)')),
                ('perm_set_second', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Permanent set 2nd cycle (%)')),
                ('load_hundred_second', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 100% elongation 2nd cycle (N/50 mm)')),
                ('perm_set_third', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Permanent set 3rd cycle (%)')),
                ('load_hundred_third', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Load at 100% elongation 3rd cycle (N/50 mm)')),
                ('lamination_str', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lamination strenght (CD) (N/25 mm)')),
            ],
            options={
                'verbose_name_plural': 'CTSups',
            },
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_prevista_inicio', models.DateField(default=datetime.date.today, verbose_name='Data Prevista de Início')),
                ('hora_prevista_inicio', models.TimeField(blank=True, default='00:00', null=True, verbose_name='Hora prevista de inicio')),
                ('data_prevista_fim', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Fim')),
                ('hora_prevista_fim', models.TimeField(blank=True, null=True, verbose_name='Hora prevista de fim')),
                ('horas_previstas_producao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Horas previstas de produção')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inico')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('op', models.CharField(max_length=200, verbose_name='Ordem de Produção')),
                ('largura', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Largura')),
                ('limsup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limite Superior')),
                ('liminf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limite Inferior')),
                ('core', models.CharField(choices=[('3"', '3"'), ('6"', '6"')], max_length=2, verbose_name='Core')),
                ('num_paletes_produzidas', models.IntegerField(default=0, verbose_name='Nº de paletes produzidas')),
                ('num_paletes_produzir', models.IntegerField(default=0, verbose_name='Nº de paletes a produzir')),
                ('num_paletes_stock_in', models.IntegerField(default=0, verbose_name='Nº de paletes de stock inseridas')),
                ('num_paletes_stock', models.IntegerField(default=0, verbose_name='Nº de paletes em stock')),
                ('num_paletes_total', models.IntegerField(default=0, verbose_name='Nº de paletes total')),
                ('tipo_emenda', models.CharField(blank=True, choices=[('Fita Preta', 'Fita Preta'), ('Fita metálica', 'Fita metálica'), ('Fita metálica e Fita Preta', 'Fita metálica e Fita Preta')], default='Fita Preta', max_length=200, null=True, verbose_name='Tipo de Emenda')),
                ('emendas', models.CharField(max_length=200, verbose_name='Emendas')),
                ('nwsup', models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici'), ('Fitesa', 'Fitesa'), ('ALBIS 23', 'ALBIS 23'), ('ALBIS 16', 'ALBIS 16'), ('Union Pillow', 'Union Pillow'), ('Union UV', 'Union UV'), ('Jacob Holm', 'Jacob Holm'), ('Nonwoven Nikoo 25gsm Spunlace 100PP', 'Nonwoven Nikoo 25gsm Spunlace 100PP'), ('Nonwoven Nikoo 28gsm Spunlace 100PP', 'Nonwoven Nikoo 28gsm Spunlace 100PP'), ('Sandler Sawabond 7059 24gsm', 'Sandler Sawabond 7059 24gsm'), ('Nonwoven ANT - ANTJET 25gsm 100PP 2200', 'Nonwoven ANT - ANTJET 25gsm 100PP 2200'), ('Nonwoven Vaporjet 25gsm Spunlace 100PP 2200', 'Nonwoven Vaporjet 25gsm Spunlace 100PP 2200')], max_length=200, null=True, verbose_name='Nonwoven Superior')),
                ('nwinf', models.CharField(blank=True, choices=[('Suominen 25 gsm', 'Suominen 25 gsm'), ('Sandler SPUNLACE 100%PP', 'Sandler SPUNLACE 100%PP'), ('BCN 70%PP/30%PE', 'BCN 70%PP/30%PE'), ('Sandler', 'Sandler'), ('PEGAS BICO 17gsm', 'PEGAS BICO 17gsm'), ('Suominen', 'Suominen'), ('BCN', 'BCN'), ('ORMA', 'ORMA'), ('PEGAS 22', 'PEGAS 22'), ('SAWASOFT', 'SAWASOFT'), ('SAWABOND', 'SAWABOND'), ('Teksis', 'Teksis'), ('Union', 'Union'), ('Radici', 'Radici'), ('Fitesa', 'Fitesa'), ('ALBIS 23', 'ALBIS 23'), ('ALBIS 16', 'ALBIS 16'), ('Union Pillow', 'Union Pillow'), ('Union UV', 'Union UV'), ('Jacob Holm', 'Jacob Holm'), ('Nonwoven Nikoo 25gsm Spunlace 100PP', 'Nonwoven Nikoo 25gsm Spunlace 100PP'), ('Nonwoven Nikoo 28gsm Spunlace 100PP', 'Nonwoven Nikoo 28gsm Spunlace 100PP'), ('Sandler Sawabond 7059 24gsm', 'Sandler Sawabond 7059 24gsm'), ('Nonwoven ANT - ANTJET 25gsm 100PP 2200', 'Nonwoven ANT - ANTJET 25gsm 100PP 2200'), ('Nonwoven Vaporjet 25gsm Spunlace 100PP 2200', 'Nonwoven Vaporjet 25gsm Spunlace 100PP 2200')], max_length=200, null=True, verbose_name='Nonwoven Inferior')),
                ('tipo_paletes', models.CharField(choices=[('970x970', '970x970')], default='970x970', max_length=200, verbose_name='Tipo de Paletes')),
                ('palete_por_palete', models.IntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='Palete por Palete')),
                ('bobines_por_palete', models.IntegerField(default=0, verbose_name='Bobines por Palete Superior ou Única')),
                ('bobines_por_palete_inf', models.IntegerField(default=0, verbose_name='Bobines por Palete Inferior')),
                ('enrolamento', models.CharField(choices=[('Anti-horário', 'Anti-horário'), ('Horário', 'Horário')], default='Anti-horario', max_length=100, verbose_name='Sentido do enrolamento')),
                ('folha_id', models.BooleanField(default=True, verbose_name='Folha de identificação de palete')),
                ('freq_amos', models.IntegerField(default=4, verbose_name='Frequência de amostragem por bobinagem')),
                ('limite_desc', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Limite Descentrado')),
                ('limite_con', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Limite Cónico')),
                ('diam_min', models.IntegerField(default=0, verbose_name='Diâmetro minimo')),
                ('diam_max', models.IntegerField(default=0, verbose_name='Diâmetro máximo')),
                ('stock', models.BooleanField(default=False, verbose_name='Stock')),
                ('ficha_processo', models.FileField(blank=True, null=True, upload_to='media/docs/process/')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='media/docs/tecnic/')),
                ('of', models.FileField(blank=True, null=True, upload_to='media/docs/of/')),
                ('coa_aprov', models.FileField(blank=True, null=True, upload_to='media/docs/coa/')),
                ('pack_list', models.FileField(blank=True, null=True, upload_to='media/docs/packlist/')),
                ('res_prod', models.FileField(blank=True, null=True, upload_to='media/docs/resumoproducao/')),
                ('ori_qua', models.FileField(blank=True, null=True, upload_to='media/docs/oriqualidade/')),
                ('tipo_transporte', models.CharField(blank=True, choices=[('Camião', 'Camião'), ('Contentor', 'Contentor')], max_length=20, null=True, verbose_name='Tipo de Transporte')),
                ('paletes_camiao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Paletes por camião')),
                ('altura_max', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Altura máxima')),
                ('paletes_sobre', models.BooleanField(default=False, verbose_name='Paletes Sobrepostas')),
                ('cintas', models.BooleanField(default=False, verbose_name='Cintas')),
                ('topo', models.CharField(blank=True, choices=[('Placa Plástico', 'Placa Plástico'), ('Placa Cartão Fino', 'Placa Cartão Fino')], max_length=50, null=True, verbose_name='Topo')),
                ('base', models.CharField(blank=True, choices=[('Placa Plástico', 'Placa Plástico'), ('Placa Cartão Fino', 'Placa Cartão Fino')], max_length=50, null=True, verbose_name='Base')),
                ('embal', models.CharField(blank=True, choices=[('Filme Estirável', 'Filme Estirável')], max_length=50, null=True, verbose_name='Embalamento')),
                ('etiqueta_bobine', models.IntegerField(default=2, verbose_name='Etiqueta por bobine')),
                ('etiqueta_palete', models.IntegerField(default=4, verbose_name='Etiqueta por palete')),
                ('etiqueta_final', models.IntegerField(default=1, verbose_name='Etiqueta final por palete')),
                ('ativa', models.BooleanField(default=False, verbose_name='Em progresso')),
                ('completa', models.BooleanField(default=False, verbose_name='Completa')),
                ('retrabalho', models.BooleanField(default=False, verbose_name='Ordem de retrabalho')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.artigo', verbose_name='Artigo')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.cliente', verbose_name='Cliente')),
                ('ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planeamento.caracteristicastecnicas', verbose_name='Caracteristicas Técnicas')),
                ('enc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.encomenda', verbose_name='Encomenda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Ordens de Produção',
            },
        ),
        migrations.CreateModel(
            name='PaletesARetrabalhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planeamento.ordemproducao', verbose_name='Ordem de Produção')),
                ('palete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.palete', verbose_name='Palete')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristicastecnicas',
            name='ctinf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planeamento.ctinf', verbose_name='Caracteristicas Técnicas Inferior'),
        ),
        migrations.AddField(
            model_name='caracteristicastecnicas',
            name='ctsup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planeamento.ctsup', verbose_name='Caracteristicas Técnicas Superior'),
        ),
        migrations.AddField(
            model_name='caracteristicastecnicas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.CreateModel(
            name='BobinesARetrabalhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrabalhar', models.BooleanField(default=True, verbose_name='Retrabalhar')),
                ('bobine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.bobine', verbose_name='Bobine')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planeamento.ordemproducao', verbose_name='Ordem de Produção')),
            ],
        ),
    ]
