# Generated by Django 3.2.8 on 2021-10-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0002_ordemproducao_ofid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='clientecod',
            field=models.CharField(max_length=15, null=True, verbose_name='Código Cliente'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='clientenome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome Cliente'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='enccod',
            field=models.CharField(max_length=25, null=True, verbose_name='Código Encomenda'),
        ),
    ]
