# Generated by Django 3.2.8 on 2021-10-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0003_auto_20211017_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='prfcod',
            field=models.CharField(max_length=25, null=True, verbose_name='Código PRF'),
        ),
    ]
