# Generated by Django 3.2.8 on 2021-10-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0004_ordemproducao_prfcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='clientenome',
            field=models.CharField(max_length=80, null=True, verbose_name='Nome Cliente'),
        ),
    ]
