# Generated by Django 3.2.8 on 2021-11-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0011_paletizacao_paletizacaodetails'),
        ('planeamento', '0005_alter_ordemproducao_clientenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='paletizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.paletizacao', verbose_name='Paletização'),
        ),
    ]
