# Generated by Django 3.2.8 on 2021-11-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0006_ordemproducao_paletizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='Status'),
        ),
    ]
