# Generated by Django 3.2.8 on 2021-11-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0017_auto_20211108_1544'),
        ('planeamento', '0007_ordemproducao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='formulacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.formulacao', verbose_name='Formulação'),
        ),
    ]
