# Generated by Django 3.2.8 on 2022-01-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0098_auto_20220118_1747'),
        ('planeamento', '0008_ordemproducao_formulacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemproducao',
            name='formulacao',
        ),
        migrations.RemoveField(
            model_name='ordemproducao',
            name='paletizacao',
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='draft_ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.tempordemfabrico', verbose_name='Draft Ordem de Producao'),
        ),
    ]
