# Generated by Django 4.0.2 on 2023-06-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0010_ordemproducao_agg_of_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='was_in_production',
            field=models.BooleanField(default=False, verbose_name='Esteve em produção'),
        ),
    ]
