# Generated by Django 4.0.2 on 2023-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0011_ordemproducao_was_in_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='certificacoes',
            field=models.CharField(max_length=200, null=True, verbose_name='Certificações'),
        ),
    ]
