# Generated by Django 4.0.2 on 2023-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0012_ordemproducao_certificacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='reported_paletes',
            field=models.IntegerField(null=True, verbose_name='Indica se o relatório de produção foi sincronizada com o SAGE'),
        ),
    ]
