# Generated by Django 4.0.2 on 2023-10-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0013_ordemproducao_reported_paletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='eef',
            field=models.CharField(max_length=17, null=True, verbose_name='Encomenda'),
        ),
    ]
