# Generated by Django 4.0.2 on 2024-03-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0014_ordemproducao_eef'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='paletizacao_id',
            field=models.IntegerField(null=True, verbose_name='Indica o esquema de embalamento'),
        ),
    ]
