# Generated by Django 4.0.2 on 2024-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0015_ordemproducao_paletizacao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='num_paletes_carga',
            field=models.IntegerField(null=True, verbose_name='Indica o nº de paletes em carga'),
        ),
    ]
