# Generated by Django 4.0.2 on 2024-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0016_ordemproducao_num_paletes_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='ignore_audit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ignore Audit'),
        ),
    ]
