# Generated by Django 4.0.2 on 2024-03-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamento', '0017_ordemproducao_ignore_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='num_paletes_carga',
            field=models.IntegerField(default=0, null=True, verbose_name='Indica o nº de paletes em carga'),
        ),
    ]
